name: Feature Request
description: Suggest a new feature or improvement
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem
      placeholder: What problem does this solve? What's missing or frustrating?
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      placeholder: Describe what you'd like to see.
    validations:
      required: true

  - type: dropdown
    id: app
    attributes:
      label: Applies to
      options:
        - Web app
        - Desktop app
        - Both

  - type: textarea
    id: context
    attributes:
      label: Additional context
      placeholder: Screenshots, mockups, links to similar implementations, etc.
